name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
      - feat/step-8

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t jsp-cafe-image:latest .

      - name: Setup known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Gradle 빌드에 필요한 Java 버전 설정

      - name: Build with Gradle
        run: ./gradlew build

      - name: Push Docker image to Docker Hub
        run: |
          docker tag jsp-cafe-image:latest ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe-image:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe-image:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe-image:latest
          HOST_IP=$(hostname -I | awk '{print $1}')
          
          IMAGE_NAME="jsp-cafe-image"
          CONTAINER_NAME="jsp-cafe-image-container"
          
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true
          
          docker run -d \
          --name $CONTAINER_NAME \
          -e HOST_IP=$HOST_IP \
          -p 8080:8080 \
          $IMAGE_NAME
