name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t jsp-cafe:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag jsp-cafe:latest ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe:latest

      - name: Deploy to EC2
        uses: appleboy/drone-ssh-action@v0.8.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe:latest
            docker stop my-running-container || true
            docker rm my-running-container || true
            docker run -d --name my-running-container ${{ secrets.DOCKER_HUB_USERNAME }}/jsp-cafe:latest
            sh /path/to/your-script.sh
